name: GlucoFlow CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      BRONZE_BUCKET: glucoflow-bronze-ci
      SILVER_BUCKET: glucoflow-silver-ci
      GOLD_BUCKET: glucoflow-gold-ci
      QUARANTINE_BUCKET: glucoflow-quarantine-ci
      ATHENA_RESULTS_BUCKET: glucoflow-bronze-ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
        working-directory: glucoflow
      - run: pytest tests/ -v --tb=short
        working-directory: glucoflow
